image: ubuntu:18.04

# List of ENVVAR
# - SSH_PRIVATE_KEY
# - PROJECT_DIR
# - SSH_HOST

stages:
  - deploy_dev

before_script:
  - test -n "$SSH_PRIVATE_KEY" || ( echo "missing variable SSH_PRIVATE_KEY" && exit 1)
  - test -n "$SSH_HOST" || ( echo "missing variable SSH_HOST" && exit 1)
  - test -n "$PROJECT_DIR" || ( echo "missing variable PROJECT_DIR" && exit 1)
  - apt-get update -qq && apt-get install -qq curl
  - which ssh-agent || apt-get install -qq openssh-client
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - touch ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy_dev:
  stage: deploy_dev
  only:
    - dev
  script:
    - ssh $SSH_HOST "cd $PROJECT_DIR && rm -rf node_modules && git pull && npm install && npm run build && pm2 start pm2.json"